# Generated by Django 4.2.4 on 2023-08-28 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("order", models.IntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="category")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
