# Generated by Django 4.2.2 on 2023-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_news"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AddField(
            model_name="news",
            name="is_banner",
            field=models.IntegerField(default=0),
        ),
    ]
